# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  slam_config = debug

else ifeq ($(config),release)
  slam_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := slam

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

slam:
ifneq (,$(slam_config))
	@echo "==== Building slam ($(slam_config)) ===="
	@${MAKE} --no-print-directory -C . -f slam.make config=$(slam_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f slam.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   slam"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"